version: '3'
networks:
  mainnetwork:
services:
  web:
    build: docker/php
    ports:
      - "12345:80"
    volumes:
      - ./src/:/var/www/html
      - ./logs/:/logs/
    links:
      - "db:database"
    networks:
      - mainnetwork
  db:
    build: docker/mysql
    networks:
      - mainnetwork
    ports:
      - "3307:3306"
      - "3306:3306"

