FROM mysql/mysql-server:latest

ENV MYSQL_USER=virtualtravelagency
ENV MYSQL_PASSWORD=virtualtravelagency
ENV MYSQL_DATABASE=virtualtravelagency
ENV MYSQL_ROOT_PASSWORD=root
#ENV MYSQL_ALLOW_EMPTY_PASSWORD="yes"
